### ISSUE TITLE
Falta informação de página inicial

### ISSUE THREAD

**Issue by TiagoJVilela** [IreneCanelas/QuizRepository#1]
Ao entrar no website pela primeira vez, é possível aceder a qualquer página, sendo a inicial desconhecida. Criando um index.php é possível definir a página principal, senão, acrescentar no readme.txt qual a página que deveremos aceder primeiro.

**Comment by sararocha25** [comment]
Obrigado pelo feedback. Resolvido. Foi alterado para index.php
