### ISSUE TITLE
Erro na página 'Conta'

### ISSUE THREAD

**Issue by TiagoJVilela** [IreneCanelas/QuizRepository#2]
Mesmo após ter sido feito o login, que, por si não apresenta dados de email ou ID no lado esquerdo, ao tentar aceder a 'Conta' o seguinte erro é apresentado.
![image](https://user-images.githubusercontent.com/61654138/82576641-d2539180-9b81-11ea-9fa5-9a03880be7d4.png)

**Comment by reislayla** [comment]
Esta página está em construção. Isto será resolvido o mais breve possível. Obrigada.

**Comment by reislayla** [comment]
Página Under Construction criada. Obrigada!
