### ISSUE TITLE
Final da quiz

### ISSUE THREAD

**Issue by TiagoJVilela** [IreneCanelas/QuizRepository#3]
Ao finalizar uma quiz, sem ter feito login, aparece a mensagem abaixo de erro, tal como o tempo continua a contar.
![image](https://user-images.githubusercontent.com/61654138/82577058-57d74180-9b82-11ea-87e6-f4201389bd41.png)

**Comment by IreneCanelas** [comment]
Obrigado pelo feedback. Resolvido.
